# Generated by Django 2.2.3 on 2021-03-16 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0006_auto_20210316_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
