# Generated by Django 2.2.3 on 2021-03-17 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0009_auto_20210316_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contato',
            name='user',
        ),
        migrations.AddField(
            model_name='contato',
            name='id_user',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
