# Generated by Django 2.2.3 on 2021-03-17 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0010_auto_20210316_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contato',
            name='id_user',
        ),
        migrations.AddField(
            model_name='contato',
            name='user_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
