# Generated by Django 2.2.3 on 2021-03-17 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0011_auto_20210316_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contato',
            name='user_id',
        ),
    ]
